### ISSUE TITLE
the version of capybara we test against prints a backtrace at rspec start time

### ISSUE THREAD

**Issue by yujinakayama** [rspec/rspec-rails#1471]
https://travis-ci.org/rspec/rspec-support/jobs/85119467

```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ cd rspec-dev/repos/rspec-rails
$ bundle exec rspec
/Users/me/Projects/rspec-dev/repos/rspec-rails/spec/spec_helper.rb:4: warning: method redefined; discarding old configuration=
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in  `<main>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in  `load'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/exe/rspec:4:in  `<top (required)>'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:41:in  `invoke'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:73:in  `run'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:88:in  `run'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:101:in  `setup'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:21:in  `configure'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:108:in  `process_options_into'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:108:in  `each'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:109:in  `block in process_options_into'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `requires='
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `each'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `block in requires='
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/spec/spec_helper.rb:15:in  `<top (required)>'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/spec/spec_helper.rb:15:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/lib/rspec/rails.rb:13:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/lib/rspec/rails/vendor/capybara.rb:2:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara/rspec.rb:1:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara.rb:5:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara.rb:318:in  `<module:Capybara>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara/dsl.rb:1:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/dsl.rb:82: warning: previous definition of feature was here
/Users/me/Projects/rspec-dev/repos/rspec-expectations/lib/rspec/matchers/dsl.rb:9: warning: method redefined; discarding old exist
/Users/me/Projects/rspec-dev/repos/rspec-expectations/lib/rspec/matchers.rb:600: warning: previous definition of exist was here
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:288: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: previous definition of subject was here
/Users/me/Projects/rspec-dev/repos/rspec-rails/spec/generators/rspec/install/install_generator_spec.rb:30: warning: method redefined; discarding old use_transactional_fixtures
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:288: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: previous definition of subject was here
Run options: include {:focus=>true}
```

Even if I remove [these lines](https://github.com/rspec/rspec-rails/blob/078b29fefb129b7942ba512cc0173b0c6d20c582/spec/spec_helper.rb#L3-L5), the backtrace is still shown:

```
$ bundle exec rspec
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in  `<main>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in  `load'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/exe/rspec:4:in  `<top (required)>'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:41:in  `invoke'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:73:in  `run'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:88:in  `run'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:101:in  `setup'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:21:in  `configure'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:108:in  `process_options_into'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:108:in  `each'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration_options.rb:109:in  `block in process_options_into'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `requires='
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `each'
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `block in requires='
    from /Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1273:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/spec/spec_helper.rb:11:in  `<top (required)>'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/spec/spec_helper.rb:11:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/lib/rspec/rails.rb:13:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/Projects/rspec-dev/repos/rspec-rails/lib/rspec/rails/vendor/capybara.rb:2:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara/rspec.rb:1:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara.rb:5:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara.rb:318:in  `<module:Capybara>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.2.1/lib/capybara/dsl.rb:1:in  `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in  `load_dependency'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `block in require'
    from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in  `require'
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/dsl.rb:82: warning: previous definition of feature was here
/Users/me/Projects/rspec-dev/repos/rspec-expectations/lib/rspec/matchers/dsl.rb:9: warning: method redefined; discarding old exist
/Users/me/Projects/rspec-dev/repos/rspec-expectations/lib/rspec/matchers.rb:600: warning: previous definition of exist was here
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:288: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: previous definition of subject was here
/Users/me/Projects/rspec-dev/repos/rspec-rails/spec/generators/rspec/install/install_generator_spec.rb:30: warning: method redefined; discarding old use_transactional_fixtures
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:288: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: method redefined; discarding old subject
/Users/me/Projects/rspec-dev/repos/rspec-core/lib/rspec/core/memoized_helpers.rb:295: warning: previous definition of subject was here
Run options: include {:focus=>true}
```

**Comment by JonRowe** [comment]
They look like Rails warnings to me?

**Comment by deivid-rodriguez** [comment]
This is a circular require warning in `capybara`. I fixed it there: https://github.com/jnicklas/capybara/pull/1622

I have no idea why the first line of the backtrace (the important one) is removed. Maybe somewhere `set_backtrace` is being called and the first line removed for some reason.

**Comment by samphippen** [comment]
@deivid-rodriguez we're still experiencing this. Do you know how we might fix it?

**Comment by deivid-rodriguez** [comment]
@samphippen It should disappear if you use capybara `2.6.0` or greater. But I remember something about you testing against the oldest `capybara` version you support. So not really sure...

**Comment by samphippen** [comment]
@deivid-rodriguez yeah, we're pinned at 2.2.1, so unless we can get the patch backported and released in to the 2.2.x series, there's nothing we can do here.

@yujinakayama WDYT about closing this?

**Comment by deivid-rodriguez** [comment]
@samphippen Maybe you can get that release out, asking is free :)

**Comment by samphippen** [comment]
This is one to fix in 4.0 by bumping our minimum version of capybara right now IMO.

**Comment by pirj** [comment]
Wondering if this is still the case. I have personally never experienced this.

**Comment by benoittgt** [comment]
It seems a stale issue. I think we should close it.

**Comment by JonRowe** [comment]
We have a relaxed constraint now, I'm closing this.
