### ISSUE TITLE
irb: warn: can't alias context from irb_context. (3.5.0.beta4 and 3.5.0 final)

### ISSUE THREAD

**Issue by marcusg** [rspec/rspec-rails#1645]
Hey,

After upgrading from ```3.5.0.beta3``` to ```3.5.0.beta4``` I receive a warning when using the ```rails console``` command like: 

```
bundle exec rails console
Loading development environment (Rails 5.0.0.rc2)
irb: warn: can't alias context from irb_context.
irb(main):001:0>
```

Version beta3 works well, the warning is only visible in beta4.

**Comment by jasnow** [comment]
Got this in your Gemfile?
```
group :development do
  gem 'web-console'
end
```

**Comment by marcusg** [comment]
@jasnow nope.

**Comment by jasnow** [comment]
That did not help - i know

**Comment by myronmarston** [comment]
That warning is coming from IRB here:

https://github.com/ruby/ruby/blob/32674b167bddc0d737c38f84722986b0f228b44b/lib/irb/extend-command.rb#L188

It's apparently happening because rspec-core, when loaded, defines `context` on the top level unless you disable monkey patching.

Can you provide a repo that repros this?  I tried reproing it in isolation and have failed so far.

**Comment by marcusg** [comment]
@myronmarston ah thanks, I'll try to create a repro the next days. Do you mean this line ```config.disable_monkey_patching!``` in ```spec_helper.rb```? It seems monkeypatching is disabled in both of my scenarios, but only with rspec-rails-3.5.0.beta4 the warning gets printed.

**Comment by myronmarston** [comment]
> Do you mean this line `config.disable_monkey_patching!` in `spec_helper.rb`? It seems monkeypatching is disabled in both of my scenarios, but only with rspec-rails-3.5.0.beta4 the warning gets printed.

Correct, that's what I meant, but I just realized why that doesn't solve the problem here: because you have to opt-in to disabling monkey patching (instead of opting in to monkey patching), the monkey patches, including `context` being defined on `main` still happen up-front, and then the config option disables them.  So it still triggers the IRB warning.

**Comment by samphippen** [comment]
hey @marcusg could you provide us with a reproduction case for this issue? Just a repository we can clone that demonstrates the problem. With that we can debug :)

**Comment by marcusg** [comment]
@samphippen yes, of course. I'll add repro steps as soon as possible.

**Comment by marcusg** [comment]
I've created a repro app https://github.com/marcusg/rspec-rails-issue-1645
- a fresh rails 5.0.0 app
- only rspec-rails added
- using rspec-rails-3.5.0.beta3 works fine
- using rspec-rails-3.5.0 produces warning when running "bundle exec rails c"

**Comment by samphippen** [comment]
Repro confirmed.

**Comment by rckv** [comment]
I've got the same warning after upgrading `rspec-rails` to 3.5.1

**Comment by myronmarston** [comment]
There's an attempted fix in #1678 -- can one of you who has ran into this issue give that a try?

**Comment by myronmarston** [comment]
Can you merge this into the 3-5 branch as well?

**Comment by JonRowe** [comment]
Done.

**Comment by marcusg** [comment]
Works for me with ```3-5-maintenance``` branch, thank you guys!

**Comment by ClaudioFloreani** [comment]
I'm still having issues with:

  * ruby 2.3.1p112
  * Rails 4.2.8
  * rspec (3.6.0)
  * rspec-core (3.6.0)
  * rspec-expectations (3.6.0)
  * rspec-mocks (3.6.0)
  * rspec-rails (3.6.0)
  * rspec-support (3.6.0)

```
$ rails c
Loading development environment (Rails 4.2.8)
irb: warn: can't alias context from irb_context.
2.3.1 :001 > exit
```

**Comment by eagleas** [comment]
Hi! This solve warning for me:

1. Add 
```
RSpec.configure do |config|
...
  config.disable_monkey_patching!
...
end
```

2. Patch in Gemfile
`gem 'rspec_junit_formatter'`
to:
`gem 'rspec_junit_formatter', require: false`

**Comment by pirj** [comment]
Also, `config.disable_monkey_patching!` will be the set by default in RSpec 4.

**Comment by x-yuri** [comment]
[`db-query-matchers`][a] also triggers this warning by requiring [`rspec/core`][b]. Do you think this line is needed? It seems like it's not.

[a]: https://github.com/civiccc/db-query-matchers
[b]: https://github.com/civiccc/db-query-matchers/blob/v0.10.0/lib/db_query_matchers/make_database_queries.rb#L1

P.S. Here's where the methods (including `context`) are supposedly added to `main`:
https://github.com/rspec/rspec-core/blob/v3.10.1/lib/rspec/core/dsl.rb#L84

**Comment by philippfrank** [comment]
Happened via `guard-rspec` for me. See https://github.com/guard/guard-rspec/issues/396.

`gem 'guard-rspec', require: false` fixed this.
