### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by joelmichael** [rspec/rspec-rails#1693]
I get this whenever I load a console with rspec 3.5.0 for some reason. Not sure if there is some configuration change possible, but it doesn't happen in 3.4.0, so we rolled back.

```
Loading development environment (Rails 4.2.7.1)
irb: warn: can't alias context from irb_context.
irb(main):001:0> 
```

**Comment by mrnugget** [comment]
See this issue: https://github.com/rspec/rspec-rails/issues/1645 -- Seems to be fixed in the `3-5-maintenance` branch and the fix has not been released yet. See commits here: https://github.com/rspec/rspec-rails/commits/3-5-maintenance

**Comment by samphippen** [comment]
@joelmichael as pointed out by @mrnugget a fix for this is merged, but has not yet been released.

**Comment by myronmarston** [comment]
@samphippen -- thoughts on cutting an rspec-rails 3.5.2 release in the next week?

**Comment by samphippen** [comment]
@myronmarston I can probably commit to doing it over the coming weekend. If you or @JonRowe can do it sooner that'd be shiny.

**Comment by JonRowe** [comment]
I've just released 3.5.2

**Comment by panaak** [comment]
the problem still persists for me

rails 4.2.7.1
rspec-rails 3.5.2

```
Loading development environment (Rails 4.2.7.1)
irb: warn: can't alias context from irb_context.
```

**Comment by JonRowe** [comment]
It's possible another gem is causing this issue for you, a vanilla rails install at `4.2.7.1` with the latest RSpec gems doesn't cause this issue.

For now I suggest making sure all of your rspec gems are update to date with:
```
bundle update rspec rspec-rails rspec-core rspec-mocks rspec-expectations rspec-support
```

If you can provide a cloneable minimal reproduction repo we'll happily reopen and have a look but for now I'd suggest remove gems one at a time until the console command runs without that warning.

**Comment by panaak** [comment]
ok, looks like [draftsman](https://github.com/liveeditor/draftsman) gem is the culprit here, warning goes away when i remove it from Gemfile.
i will open an issue there i guess.
